snowdbt_homecredit_project:
  outputs:
    dev:
      account: WBRJGLN-KZ07121
      database: HOMECREDIT_DB
      password: '@S11q15a100000'
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: MASHUKOOR
      warehouse: HOMECREDIT_WH
  target: dev
